version: '3.8'

services:
  postgres-qa-dev:
    image: postgres:15
    container_name: postgres-qa-dev
    env_file:
      - .env
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen gestionado por Docker
    restart: always
    networks:
      - my-network  # Especificamos la misma red para que se puedan comunicar

volumes:
  postgres_data:  # Docker se encarga de gestionarlo
    external: false

networks:
  my-network:   # Definimos la red
    driver: bridge
